version: '3.3'

services:
  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: chaux
      MONGO_INITDB_ROOT_PASSWORD: lolita2019.
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
